# this is your configuration file that gives instructions to jekyll
brand_color: '#f05f40'
featured_color: red
light_color: grey
font_family: 'Courier New'
heading_font_size: 18px
body_font_size: 18px

class:
  - stuffed-toys
  - christmas-decorations
  - bags-and-purses
  - decorative-and-learning-strings
  - mobiles
  - clothing-and-scarves
  - hand-puppets
  - books-and-dvd

# here list all of your categories
categories:
- food
- wine
- travel
- chocolate
- Volenters
- Employes

# here list any additional collections you create
collections:
  - products
  - tours
  - sponsor

collections:
  products:
    output: true
  tours:
    output: false
  peoples:
    output: false
  sponsor:
    output: false
# here we can set defaults for our pages, posts of collection items
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: "7 Women"
      description: "Young Australian social entrepreneur Stephanie Woollard began Seven Women at only 22, after meeting seven disabled women operating out of a tin shed in Kathmandu struggling to make a living and enduring harsh discrimination. Since 2006, Seven Women has been working to empower marginalised Nepalese women through quipping them with the skills and know how to thrive."
      keywords: ""
      featured-image_path: ""
      preFormHeading: "Get in touch"
  -
    scope:
      path: ""
      type: "posts" # this will apply to all posts
    values:
      layout: post
      title: ""
      categories: ""
      author: "Joe"
      image_path: ""
  -
    scope:
      path: ""
      type: "products" # this will apply to all products
    values:
      layout: "product-page"
      _comments:
        title: This is the name of the product. it will apera on the browser tab and on the store page.
        description: This will show up if some one googles this product and it comes up on a google search page.
        class: This is where you put in the type of item it is and allows it to be filtered by that type.
        id: This is a uneice number that snipcart needs to prosece the product.
        gallery: This is where we place images that will show up on the product page. The first one will be on the store page also.
      title: ""
      description: ""
      price: ""
      type: ""
      image_path: ""
      class:
        - stuffed-toys
        - christmas-decorations
        - bags-and-purses
        - decorative-and-learning-strings
        - mobiles
        - clothing-and-scarves
        - hand-puppets
        - books-and-dvd
